### ISSUE TITLE
Add tolerance when scheduling pods 

### ISSUE THREAD

**Issue by yzaccc** [K8sbykeshed/k8s-service-validator#119]
Currently the testing pods are ignoring taints of nodes, which causes each node with get one testing pod deployed on, which needs to be improved, as some nodes in the production environment cannot get touched with taints like "noschedule".

Solution:
- Stop ignoring taints, stop adding node name in the pod specs
- Add formal tolerance for the pods
- - tolerate taint:
```
- taints:
  - effect: NoSchedule
    key: os
    value: windows
```
